export const LandConfig = {
  width: 2724,
  height: 2292,
};

export const AreaRect = [
  {
    lv: 1,
    empty: false,
    width: 1100,
    height: 500,
    left: 166,
    bottom: 244,
    cloud: {
      width: 800,
      height: 498,
      offset: { x: { min: -100, max: 100 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: -1060,
      mapY: 754,
      left: 0,
      top: 220,
      width: 276,
      height: 280,
      content: `On a coast shimmering with golden light, a massive vessel named the "Genesis Ship" lies stranded, its hull buried by wind and sand, surrounded only by a few fragile saplings. This ship once carried the earliest digital dreams, now fallen silent and desolate. Players must gather energy to repair the ship and plant protective trees. As energy flows in, greenery spreads, the ship glows anew, and the coast becomes the starting point of a new world.`,
      bg: '#CF5F18',
      borderStart: '#FFAB76',
      borderEnd: '#AF4F11',
      icon: {
        url: '/projects/mint-forest/images/map/building/1.png',
        width: 330,
      },
      name: {
        text: 'GENESIS SHIP',
        color: '#FFD71A',
        size: '48px',
      },
    },
  },
  {
    lv: 2,
    empty: false,
    width: 700,
    height: 360,
    left: 420,
    bottom: 780,
    cloud: {
      width: 540,
      height: 420,
      offset: { x: { min: -100, max: 100 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: -690,
      mapY: 130,
      left: 120,
      top: 0,
      width: 270,
      height: 210,
      content: `In a deep and mysterious forest, sparse pumpkin vines wind around ancient trees, bearing a few unique pumpkins. The forest lies in silence, lacking vitality, with only faint glimmers of pumpkin light flickering in the shadows. Players must gather energy to grow more pumpkin vines and awaken the forest’s dormant spirit. As energy flows in, the vines spread across the tree trunks, pumpkins glow brilliantly, and the forest transforms into a magical realm where nature and digital wonder intertwine.`,
      bg: '#CBA900',
      borderStart: '#FFD60A',
      borderEnd: '#FFE047',
      icon: {
        url: '/projects/mint-forest/images/map/building/2.png',
        width: 400,
      },
      name: {
        text: 'DEFI PUMPKIN',
        color: '#F4FF1A',
        size: '48px',
      },
    },
  },
  {
    lv: 3,
    empty: false,
    width: 800,
    height: 360,
    left: 450,
    bottom: 1140,
    cloud: {
      width: 480,
      height: 150,
      offset: { x: { min: -100, max: 100 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: -260,
      mapY: -206,
      left: 500,
      top: 26,
      width: 290,
      height: 260,
      content: `Hidden deep within the forest lies an abandoned village known as “DAO Town.” The wooden cabins are in disrepair, surrounded by sparse trees and silence. Once a thriving hub of self-governance for forest dwellers, the town now lies dormant. Players must gather energy to plant new trees, repair the cabins, and revive the spirit of the town. As energy flows in, the forest flourishes, lights flicker back on, and the town regains its vibrant, decentralized vitality.`,
      bg: '#11B5EB',
      borderStart: '#45C7F2',
      borderEnd: '#7ED8F6',
      icon: {
        url: '/projects/mint-forest/images/map/building/3.png',
        width: 352,
      },
      name: {
        text: 'DAO TOWN',
        color: '#19FFC5',
        size: '48px',
      },
    },
  },
  {
    lv: 4,
    empty: false,
    width: 750,
    height: 540,
    left: 228,
    bottom: 1500,
    cloud: {
      width: 510,
      height: 390,
      offset: { x: { min: -100, max: 100 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: -566,
      mapY: -574,
      left: 434,
      top: 152,
      width: 290,
      height: 240,
      content: `Deep within a lush forest lies "Smart Contract Paradise," a wondrous realm woven from digital rules. Once, trees and code thrived together here, but now it has faded due to depleted energy, with sparse vegetation. Players must gather energy to plant new trees and awaken dormant digital nodes. As energy flows in, streams of light flicker among the branches, transforming the forest into an automated, thriving paradise where nature and intelligence resonate in harmony.`,
      bg: '#0BC556',
      borderStart: '#1CF272',
      borderEnd: '#56F596',
      icon: {
        url: '/projects/mint-forest/images/map/building/4.png',
        width: 390,
      },
      name: {
        text: 'SMART CONTRACT PARADISE',
        color: '#FFFF3B',
        size: '32px',
      },
    },
  },
  {
    lv: 5,
    empty: false,
    width: 600,
    height: 440,
    left: 950,
    bottom: 1500,
    cloud: {
      width: 420,
      height: 390,
      offset: { x: { min: -100, max: 100 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: -50,
      mapY: -580,
      width: 210,
      height: 160,
      left: 234,
      top: 140,
      content: `At the edge of the forest, "NFT Garden" quietly blooms, once home to unique digital flowers that have now withered due to lost energy, leaving only a few dry branches. Players must gather energy to plant new flowers and awaken the garden’s digital roots. As energy flows in, flowers blossom, each glowing with a distinct light, turning the forest into an eternal artistic paradise.`,
      bg: '#7CE9BE',
      borderStart: '#48E0A3',
      borderEnd: '#22C986',
      icon: {
        url: '/projects/mint-forest/images/map/building/5.png',
        width: 332,
      },
      name: {
        text: 'NFT GARDEN',
        color: '#4C984E',
        size: '48px',
      },
    },
  },
  {
    lv: 6,
    empty: false,
    width: 800,
    height: 500,
    left: 1000,
    bottom: 2000,
    cloud: {
      width: 570,
      height: 420,
      offset: { x: { min: -100, max: 100 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: 120,
      mapY: -1100,
      width: 300,
      height: 400,
      left: 320,
      top: 42,
      content: `At the highest point of the forest stands "Layer2 Snow Mountain," its snow-capped peak once a hub of flowing energy, now silenced by the cold, with only a few frozen pine trees remaining. Players must gather energy to plant hardy trees and activate the digital pathways at the summit. As energy flows in, the ice melts, the pine forest revives, and the mountain becomes a thriving pinnacle of efficient connection.`,
      bg: '#B2CDDB',
      borderStart: '#89B3C8',
      borderEnd: '#5F98B4',
      icon: {
        url: '/projects/mint-forest/images/map/building/6.png',
        width: 320,
      },
      name: {
        text: 'LAYER2 SNOW MOUNTAIN',
        color: '#326069',
        size: '36px',
      },
    },
  },
  {
    lv: 7,
    empty: false,
    width: 1100,
    height: 600,
    left: 1580,
    bottom: 1500,
    cloud: {
      width: 660,
      height: 420,
      offset: { x: { min: -100, max: 100 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: 930,
      mapY: -720,
      width: 500,
      height: 500,
      left: 470,
      top: 0,
      content: `At the enigmatic edge of the forest, the "Metaverse Forest Waterfall" cascades down, its waters once reflecting the fusion of virtual and real worlds. This place was a nexus of infinite possibilities, but now the waterfall has dried up, and the surrounding vegetation is sparse. Players must gather energy to plant new trees and revive the waterfall’s digital source. As energy flows in, the waters return, transforming the forest into an immersive metaverse paradise.`,
      bg: '#496365',
      borderStart: '#638688',
      borderEnd: '#83A3A5',
      icon: {
        url: '/projects/mint-forest/images/map/building/7.png',
        width: 360,
      },
      name: {
        text: 'METAVERSE FOREST WATERFALL',
        color: '#00FF6A',
        size: '30px',
      },
    },
  },
  {
    lv: 8,
    empty: false,
    width: 600,
    height: 450,
    left: 1790,
    bottom: 1050,
    cloud: {
      width: 480,
      height: 360,
      offset: { x: { min: -100, max: 100 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: 700,
      mapY: -160,
      width: 190,
      height: 250,
      left: 170,
      top: 42,
      content: `In a secluded corner of the forest stands the "Privacy Cabin," once a sanctuary of digital security, now overgrown with vines and surrounded by sparse trees. Players must gather energy to plant guardian trees and restore the cabin’s protective barrier. As energy flows in, the vines recede, the cabin glows softly, and the forest becomes a tranquil haven of privacy.`,
      bg: '#C8DEE6',
      borderStart: '#9DC4D2',
      borderEnd: '#73ABBF',
      icon: {
        url: '/projects/mint-forest/images/map/building/8.png',
        width: 286,
      },
      name: {
        text: 'PRIVACY CABIN',
        color: '#345966',
        size: '48px',
      },
    },
  },
  {
    lv: 9,
    empty: false,
    width: 580,
    height: 380,
    left: 1220,
    bottom: 960,
    cloud: {
      width: 360,
      height: 300,
      offset: { x: { min: -20, max: 20 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: 180,
      mapY: 60,
      width: 220,
      height: 200,
      left: 210,
      top: 160,
      content: `Deep within an ancient forest, "Staking Dragon Eggs" rest in a rocky nest, these mysterious eggs once brimming with power, now sealed by frost, with withered vegetation around. Players must gather energy to plant warming trees and thaw the eggs’ icy prison. As energy flows in, the frost melts, the forest revives, and the eggs hatch into radiant new life, filling the woods with vitality.`,
      bg: '#476512',
      borderStart: '#6A981B',
      borderEnd: '#8ECC24',
      icon: {
        url: '/projects/mint-forest/images/map/building/9.png',
        width: 378,
      },
      name: {
        text: 'STAKING DRAGON EGG',
        color: '#F8F6D1',
        size: '40px',
      },
    },
  },
  {
    lv: 10,
    empty: false,
    width: 1300,
    height: 560,
    left: 1350,
    bottom: 380,
    cloud: {
      width: 810,
      height: 510,
      offset: { x: { min: -100, max: 100 }, y: { min: -50, max: 50 } },
    },
    building: {
      mapX: 1000,
      mapY: 360,
      width: 350,
      height: 250,
      left: 780,
      top: 30,
      content: `At the vibrant edge of the forest, clusters of "Web3 Ecosystem Mushroom Houses" stand, once the heart of a digital ecosystem, now shrunken from lack of energy, surrounded by withered grass. Players must gather energy to plant new trees and activate the mushroom houses’ network. As energy flows in, the mushroom houses regrow, their lights linking into a web, transforming the forest into a thriving Web3 ecological paradise.`,
      bg: '#D1B192',
      borderStart: '#D2B393',
      borderEnd: '#D29393',
      icon: {
        url: '/projects/mint-forest/images/map/building/10.png',
        width: 322,
      },
      name: {
        text: 'WEB3 ECOSYSTEM MUSHROOM HOUSE',
        color: '#8D3928',
        size: '24px',
      },
    },
  },
];
